name: "Build"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: "extra-platforms = aarch64-linux"
      - run: nix flake check --all-systems
      - run: nix build .#packages.x86_64-linux.default && docker load < ./result && docker push -a ghcr.io/xedon/borg
      - run: nix build .#packages.aarch64-linux.default && docker load < ./result && docker push -a ghcr.io/xedon/borg
